### ISSUE TITLE
How to build the project ?

### ISSUE THREAD

**Issue by pythonbrad** [stroke-input/stroke-input-android#10]
### Problem
When i try to build in using android studio, i got this error.
> Unable to find Gradle tasks to build: [:]. 
			Build mode: ASSEMBLE. 
			Tests: All.
### System configuration
- Android Studio Dolphin | 2021.3.1 Patch 1
- Linux
- Android API 33

**Comment by yawnoc** [comment]
- What is the output if you run `./gradlew assembleDebug` in your terminal?
- Does this happen with other Android Studio projects (say some other app hosted on F-Droid)?

**Comment by pythonbrad** [comment]
> - What is the output if you run `./gradlew assembleDebug` in your terminal?
> 

Thanks, it works!
