### ISSUE TITLE
Develop into something like Multiling O Keyboard?

### ISSUE THREAD

**Issue by GrimPixel** [stroke-input/stroke-input-android#15]
For other open-source multilingual keyboards programs, when asked about supporting CJKV, their developers all appear indifferent. I see this as a chance for those who care about CJKV input on Android.
If you could extend the functionalities of the stroke-input, to support more effective input methods and different keyboard layouts, it would be much more competitive. How about your thoughts?

**Comment by yawnoc** [comment]
From the open-source developer's perspective, it is better not to implement a feature than to implement it badly. I think that is why there is pushback against support for CJKV. Unless the developer is very familiar with those languages, there is too much risk of ending up with a bad implementation.

In the case of Stroke Input Method, I created it out of dissatisfaction with existing implementations on the market (closed-source, missing characters, inconsistent stroke sequences, etc.). Having satisfied that business need, and to keep things minimalist, I do not intend on expanding to other input methods.

Finally, at least on newer Android phones, I believe when typing there appears a small button at the bottom of the screen which allows for quick switching between keyboards. Moreover, many keyboards (including Stroke Input Method) have long-press-space-bar bring up the keyboard switching menu.

So the only thing I can suggest is to install all the various input methods you want, and then switch between them on demand.

**Comment by GrimPixel** [comment]
Thaeks for explaining that. For now, I can still use Multiling O Keyboard like ten years before.
