### ISSUE TITLE
[功能请求] TTS

### ISSUE THREAD

**Issue by Pantyhose-X** [stroke-input/stroke-input-android#3]
1. `输入空格` 后TTS朗读单词，`输入回车键`后朗读句子。
2. 应用于语言学习。发音纠正，这样可以纠正发音和加深记忆，
3. 母语不是英语。需要学习英语，市场非常大 

例子

https://user-images.githubusercontent.com/42504385/132130706-a1a8ec10-416a-4711-b5d3-c91086e9710f.mp4

https://user-images.githubusercontent.com/42504385/127757873-c3c076d3-ce73-40b1-8f57-423459fc0c2f.MP4

开源 TTS
[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts)
[Mozilla 的 Text-to-Speech](https://github.com/mozilla/TTS)
[coqui-ai TTS](https://github.com/coqui-ai/TTS)

**Comment by yawnoc** [comment]
此輸入法，務乎簡樸，旨在書寫中文，而非敎讀英語。

今 apk 不越 3MB。
Google TTS 有 47MB， Mozilla TTS 300MB，已大之十倍百倍。
況且，予編程功力有限，不熟乎 AI，恐再十年而未之成也。

欲學英文者，請另索。

---

This input method seeks to be minimalist. The aim is to allow input of Chinese, not the teaching of English.

Currently the apk is under 3MB.
Google TTS is 47 MB; Mozilla TTS, 300 MB. These are already ten and a hundred times as big.
Moreover, my programming ability is limited. I am unfamiliar with AI, and it would take many years to complete such an endeavour.

If you want an English learning app, please seek elsewhere.
