### ISSUE TITLE
Add a retract-keyboard key

### ISSUE THREAD

**Issue by J4gQBqqR** [stroke-input/stroke-input-android#5]
Users might have the navigation bar hidden on some distros. It would be useful to add a hidden key for keyboard.

**Comment by yawnoc** [comment]
Sorry I don't quite understand what you are requesting. Perhaps a screenshot would help.

1. > Users might have the navigation bar hidden on some distros.

   What navigation bar are you referring to, and how does this relate to the keyboard?

2. > It would be useful to add a hidden key for keyboard.

   What do you mean by a hidden key for keyboard?

**Comment by J4gQBqqR** [comment]
![Screenshot_20220208-172614-084](https://user-images.githubusercontent.com/77554817/153086090-a5dba04b-9903-47a5-8e77-b6d4ac7e7570.png)

I am referring to the blue area in the screenshot. As you can see, when using guesture navigation, this area can be hidden on numerous OS. This area usually has a keyboard switch key and a keyboard retract/hidden key.

When navigation bar is hidden, user does not have access to the retract key anymore.

**Comment by yawnoc** [comment]
Does the Back Gesture not retract the keyboard?
(If so, it's Google's fault for committing the phone equivalent of "don't break the back button".)

**Comment by J4gQBqqR** [comment]
Thank you for your reply. 
The back guesture surely retract the keybaord. 
Not sure if a standalone retract key seems resonable to you under this scenario.

At the end of the day, it is your call as a developper to determine what to support and what not to. We as users fully understand that.
